<a href="https://colab.research.google.com/github/Truongos/deep-learning-challenge/blob/main/neuralnetworkmode_OPTIMIZED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [7]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [8]:
# Determine the number of unique values in each column
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [9]:
# Look at APPLICATION_TYPE value counts for binning
type_counts = application_df['APPLICATION_TYPE'].value_counts()
type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [10]:
# Set a cutoff value (you can adjust this based on your dataset)
application_types_to_replace = list(type_counts.iloc[8:].index)
cutoff_value = 528


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# # Look at APPLICATION_TYPE value counts
# app_type_counts = application_df['APPLICATION_TYPE'].value_counts()
# print(app_type_counts)

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [11]:
# Look at CLASSIFICATION value counts for binning
classification_types = application_df['CLASSIFICATION'].value_counts()
classification_types

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [12]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classifications_update = classification_types.loc[classification_types > 1]
classifications_update

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [13]:
# Set a cutoff value (you can choose a different value based on your dataset)
classifications_to_replace = list(classification_types.iloc[5:].index)
cutoff_value_classifications = 1883

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [14]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies=pd.get_dummies(application_df)
dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [15]:
# Define features (X) and target variable (y)
y = dummies['IS_SUCCESSFUL'].values
X = dummies.drop(columns="IS_SUCCESSFUL").values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [18]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 8
hidden_nodes_layer3 = 4

nn = tf.keras.models.Sequential()

# First hidden layer

nn.add(
   tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)
# Second hidden layer

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# third Layer
nn.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 10)                440

 dense_5 (Dense)             (None, 8)                 88

 dense_6 (Dense)             (None, 4)                 36

 dense_7 (Dense)             (None, 1)                 5

=================================================================
Total params: 569 (2.22 KB)
Trainable params: 569 (2.22 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [19]:
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [20]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 4s 3ms/step - loss: 0.6232 - accuracy: 0.6735 - val_loss: 0.5643 - val_accuracy: 0.7302
Epoch 2/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5691 - accuracy: 0.7239 - val_loss: 0.5529 - val_accuracy: 0.7352
Epoch 3/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5615 - accuracy: 0.7251 - val_loss: 0.5496 - val_accuracy: 0.7391
Epoch 4/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5582 - accuracy: 0.7284 - val_loss: 0.5462 - val_accuracy: 0.7385
Epoch 5/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5561 - accuracy: 0.7277 - val_loss: 0.5440 - val_accuracy: 0.7378
Epoch 6/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5548 - accuracy: 0.7293 - val_loss: 0.5447 - val_accuracy: 0.7367
Epoch 7/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5537 - accuracy: 0.7276 - val_loss: 0.5438 - val_accuracy: 0.7411
Epoch 8/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5530 - accuracy: 0.7294 - val_loss: 0.5423 - val_accuracy: 0.7396
Epoch 9/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5522 - accuracy: 0.7299 - val_loss: 0.5429 - val_accuracy: 0.7391
Epoch 10/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5516 - accuracy: 0.7305 - val_loss: 0.5419 - val_accuracy: 0.7378
Epoch 11/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5507 - accuracy: 0.7306 - val_loss: 0.5417 - val_accuracy: 0.7401
Epoch 12/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5506 - accuracy: 0.7308 - val_loss: 0.5400 - val_accuracy: 0.7416
Epoch 13/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5503 - accuracy: 0.7304 - val_loss: 0.5414 - val_accuracy: 0.7383
Epoch 14/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5502 - accuracy: 0.7301 - val_loss: 0.5403 - val_accuracy: 0.7416
Epoch 15/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5497 - accuracy: 0.7314 - val_loss: 0.5417 - val_accuracy: 0.7422
Epoch 16/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5497 - accuracy: 0.7314 - val_loss: 0.5399 - val_accuracy: 0.7414
Epoch 17/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5489 - accuracy: 0.7314 - val_loss: 0.5416 - val_accuracy: 0.7422
Epoch 18/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7323 - val_loss: 0.5396 - val_accuracy: 0.7391
Epoch 19/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5484 - accuracy: 0.7319 - val_loss: 0.5399 - val_accuracy: 0.7403
Epoch 20/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5482 - accuracy: 0.7305 - val_loss: 0.5401 - val_accuracy: 0.7398
Epoch 21/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5481 - accuracy: 0.7323 - val_loss: 0.5396 - val_accuracy: 0.7383
Epoch 22/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5474 - accuracy: 0.7314 - val_loss: 0.5411 - val_accuracy: 0.7398
Epoch 23/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5473 - accuracy: 0.7322 - val_loss: 0.5411 - val_accuracy: 0.7396
Epoch 24/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5474 - accuracy: 0.7320 - val_loss: 0.5407 - val_accuracy: 0.7396
Epoch 25/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5473 - accuracy: 0.7322 - val_loss: 0.5388 - val_accuracy: 0.7429
Epoch 26/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5470 - accuracy: 0.7337 - val_loss: 0.5393 - val_accuracy: 0.7427
Epoch 27/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5473 - accuracy: 0.7319 - val_loss: 0.5388 - val_accuracy: 0.7398
Epoch 28/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5467 - accuracy: 0.7320 - val_loss: 0.5394 - val_accuracy: 0.7419
Epoch 29/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5467 - accuracy: 0.7328 - val_loss: 0.5383 - val_accuracy: 0.7432
Epoch 30/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5465 - accuracy: 0.7331 - val_loss: 0.5395 - val_accuracy: 0.7406
Epoch 31/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5464 - accuracy: 0.7332 - val_loss: 0.5381 - val_accuracy: 0.7437
Epoch 32/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5463 - accuracy: 0.7310 - val_loss: 0.5408 - val_accuracy: 0.7401
Epoch 33/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7304 - val_loss: 0.5372 - val_accuracy: 0.7450
Epoch 34/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5464 - accuracy: 0.7313 - val_loss: 0.5386 - val_accuracy: 0.7450
Epoch 35/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5462 - accuracy: 0.7305 - val_loss: 0.5381 - val_accuracy: 0.7422
Epoch 36/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5461 - accuracy: 0.7327 - val_loss: 0.5391 - val_accuracy: 0.7393
Epoch 37/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5459 - accuracy: 0.7319 - val_loss: 0.5385 - val_accuracy: 0.7422
Epoch 38/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5458 - accuracy: 0.7321 - val_loss: 0.5377 - val_accuracy: 0.7424
Epoch 39/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7314 - val_loss: 0.5393 - val_accuracy: 0.7429
Epoch 40/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7319 - val_loss: 0.5398 - val_accuracy: 0.7437
Epoch 41/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7317 - val_loss: 0.5391 - val_accuracy: 0.7429
Epoch 42/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5458 - accuracy: 0.7314 - val_loss: 0.5388 - val_accuracy: 0.7432
Epoch 43/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7318 - val_loss: 0.5379 - val_accuracy: 0.7450
Epoch 44/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7316 - val_loss: 0.5380 - val_accuracy: 0.7463
Epoch 45/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5453 - accuracy: 0.7325 - val_loss: 0.5395 - val_accuracy: 0.7424
Epoch 46/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5452 - accuracy: 0.7309 - val_loss: 0.5383 - val_accuracy: 0.7455
Epoch 47/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7318 - val_loss: 0.5396 - val_accuracy: 0.7435
Epoch 48/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5447 - accuracy: 0.7318 - val_loss: 0.5376 - val_accuracy: 0.7476
Epoch 49/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7321 - val_loss: 0.5396 - val_accuracy: 0.7414
Epoch 50/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7305 - val_loss: 0.5396 - val_accuracy: 0.7440
Epoch 51/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5449 - accuracy: 0.7308 - val_loss: 0.5414 - val_accuracy: 0.7409
Epoch 52/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5446 - accuracy: 0.7320 - val_loss: 0.5395 - val_accuracy: 0.7445
Epoch 53/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5446 - accuracy: 0.7308 - val_loss: 0.5386 - val_accuracy: 0.7429
Epoch 54/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5449 - accuracy: 0.7313 - val_loss: 0.5398 - val_accuracy: 0.7432
Epoch 55/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7315 - val_loss: 0.5389 - val_accuracy: 0.7416
Epoch 56/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7322 - val_loss: 0.5398 - val_accuracy: 0.7427
Epoch 57/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5447 - accuracy: 0.7324 - val_loss: 0.5389 - val_accuracy: 0.7450
Epoch 58/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7326 - val_loss: 0.5407 - val_accuracy: 0.7427
Epoch 59/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7320 - val_loss: 0.5379 - val_accuracy: 0.7422
Epoch 60/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5442 - accuracy: 0.7324 - val_loss: 0.5389 - val_accuracy: 0.7398
Epoch 61/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5441 - accuracy: 0.7314 - val_loss: 0.5394 - val_accuracy: 0.7406
Epoch 62/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5440 - accuracy: 0.7326 - val_loss: 0.5418 - val_accuracy: 0.7427
Epoch 63/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7322 - val_loss: 0.5392 - val_accuracy: 0.7411
Epoch 64/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7304 - val_loss: 0.5380 - val_accuracy: 0.7440
Epoch 65/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7325 - val_loss: 0.5375 - val_accuracy: 0.7445
Epoch 66/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7319 - val_loss: 0.5396 - val_accuracy: 0.7422
Epoch 67/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5439 - accuracy: 0.7330 - val_loss: 0.5384 - val_accuracy: 0.7419
Epoch 68/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5435 - accuracy: 0.7322 - val_loss: 0.5399 - val_accuracy: 0.7401
Epoch 69/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5439 - accuracy: 0.7320 - val_loss: 0.5394 - val_accuracy: 0.7414
Epoch 70/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5439 - accuracy: 0.7301 - val_loss: 0.5393 - val_accuracy: 0.7440
Epoch 71/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5439 - accuracy: 0.7326 - val_loss: 0.5393 - val_accuracy: 0.7437
Epoch 72/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7335 - val_loss: 0.5405 - val_accuracy: 0.7427
Epoch 73/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7324 - val_loss: 0.5393 - val_accuracy: 0.7414
Epoch 74/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7320 - val_loss: 0.5409 - val_accuracy: 0.7424
Epoch 75/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5440 - accuracy: 0.7323 - val_loss: 0.5385 - val_accuracy: 0.7391
Epoch 76/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5440 - accuracy: 0.7325 - val_loss: 0.5386 - val_accuracy: 0.7396
Epoch 77/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5434 - accuracy: 0.7329 - val_loss: 0.5389 - val_accuracy: 0.7416
Epoch 78/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7315 - val_loss: 0.5382 - val_accuracy: 0.7432
Epoch 79/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7335 - val_loss: 0.5380 - val_accuracy: 0.7411
Epoch 80/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7337 - val_loss: 0.5387 - val_accuracy: 0.7429
Epoch 81/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7332 - val_loss: 0.5390 - val_accuracy: 0.7403
Epoch 82/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7339 - val_loss: 0.5403 - val_accuracy: 0.7403
Epoch 83/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5434 - accuracy: 0.7328 - val_loss: 0.5395 - val_accuracy: 0.7385
Epoch 84/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5431 - accuracy: 0.7320 - val_loss: 0.5381 - val_accuracy: 0.7419
Epoch 85/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5430 - accuracy: 0.7333 - val_loss: 0.5403 - val_accuracy: 0.7401
Epoch 86/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7312 - val_loss: 0.5388 - val_accuracy: 0.7403
Epoch 87/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7322 - val_loss: 0.5401 - val_accuracy: 0.7362
Epoch 88/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7335 - val_loss: 0.5390 - val_accuracy: 0.7414
Epoch 89/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7338 - val_loss: 0.5378 - val_accuracy: 0.7419
Epoch 90/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7339 - val_loss: 0.5397 - val_accuracy: 0.7393
Epoch 91/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5430 - accuracy: 0.7324 - val_loss: 0.5396 - val_accuracy: 0.7406
Epoch 92/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5429 - accuracy: 0.7328 - val_loss: 0.5395 - val_accuracy: 0.7398
Epoch 93/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5432 - accuracy: 0.7332 - val_loss: 0.5392 - val_accuracy: 0.7411
Epoch 94/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5431 - accuracy: 0.7330 - val_loss: 0.5388 - val_accuracy: 0.7388
Epoch 95/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5428 - accuracy: 0.7332 - val_loss: 0.5401 - val_accuracy: 0.7396
Epoch 96/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5429 - accuracy: 0.7318 - val_loss: 0.5396 - val_accuracy: 0.7391
Epoch 97/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5427 - accuracy: 0.7325 - val_loss: 0.5381 - val_accuracy: 0.7422
Epoch 98/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5426 - accuracy: 0.7332 - val_loss: 0.5391 - val_accuracy: 0.7403
Epoch 99/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5429 - accuracy: 0.7327 - val_loss: 0.5384 - val_accuracy: 0.7406
Epoch 100/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7330 - val_loss: 0.5394 - val_accuracy: 0.7419

In [21]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5597 - accuracy: 0.7286 - 411ms/epoch - 2ms/step
Loss: 0.5597404837608337, Accuracy: 0.7286297082901001

In [22]:
# Assuming 'nn' is your trained model

# Save the model to an HDF5 file
nn.save('deeplearningnn.h5')

from google.colab import files

# Download the saved model file
files.download('deeplearningnn.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(